server:
  port: ${port:18080}
spring:
  datasource:
    driverClassName : com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_IP:47.100.57.92}:${MYSQL_PORT:3306}/sakila?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${name:root}
    password: ${password:root}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: Exam1.domain
